### PR TITLE
Started work on first set computation

### PR DESCRIPTION
**Pull request by ptersilie**
This branch is not finished yet. The next step would be to cache already calculated first sets within the first method.

### CODE REVIEW

**Comment by ltratt** [comment]
I've pushed a new approach but it's not directly comparable, and takes a very different approach (it returns a complete FIRSTS set, so you never need to calculate anything afterwards). I didn't really understand the FIRSTS calculation you were using, so I had to go by Wikipedia's definition. The commit has more details. There is one bit that feels a bit inefficient due to a clone() that I would prefer not to do. Maybe I'll wake up tomorrow and understand ways around the borrow checker in such cases... Anyway, feel free to use or not as you wish!

**Comment by ltratt** [comment]
As well as tests that pass, we should probably add a few tests that fail to check that we're not letting through subtly wrong inputs?

**Comment by ltratt** [comment]
Looking again at the code, I'm not sure why we can't use String instead of Symbol (which would make the code simpler and use less memory). After all, the output of FIRSTS is all about terminals. Epsilons are easily represented by "". Language boxes, I presume, are indistinguishable from any other terminal type?

**Comment by ptersilie** [comment]
I thought about this as well but then realised that we get clashes if someone uses the same name of a terminal type and a language box type, e.g.
```
rule : "sql" | <sql>
```

The question is, I guess, if we want language boxes to share the same namespace as terminals. In Eco at the moment they don't.

**Comment by ltratt** [comment]
Interesting point. A related question is whether terminals and nonterminals share the same namespace. I guess the answer is "they shouldn't", but I must admit that I haven't thought about it before.

One thing that I'm nervous / curious about is whether language boxes should be baked into the LR backend (i.e. the table generator). One possibility is to say "the backend shouldn't know anything about language boxes". I guess then a front-end that wanted to use them (or any similar mechanism) could simply perform some guaranteed-unique renaming (e.g. prepending language box terminals with `$$LB$$`)? In other words, maybe the lrpar library can always have the illusion that there are only terminals and nonterminals?

**Comment by ltratt** [comment]
I've just pushed 78a9eab which I think fixes a nasty, subtle bug (I've spent a couple of hours looking at that bit of code). But I might be very wrong, so please check carefully.

**Pull request merged**
