### PR TITLE
Include the "-y" option in the program's usage statement.

### PR DESCRIPTION
**Pull request by ltratt**
I forgot what the option was and had to look at the source code...

### CODE REVIEW

**Comment by ptersilie** [comment]
How does the user know what the variants are?

**Comment by ltratt** [comment]
Good point. I could do `[-y <eco|original>]`?

**Comment by ptersilie** [comment]
That or add more usage info.

**Comment by ltratt** [comment]
OK, see if that new commit works for you.

**Comment by ptersilie** [comment]
Yep looks good.

**Comment by ptersilie** [comment]
Ah crap! Didn't wait for the rebase.

**Comment by ltratt** [comment]
Oh well, too late now.

**Comment by ptersilie** [comment]
Sorry.

**Pull request merged**
