### PR TITLE
Corchuelo cleanup

### PR DESCRIPTION
**Pull request by ltratt**
This PR contains one very simple and one not-so-simple-but-not-that-complex-either changes to the Corchuelo recoverer.

### CODE REVIEW

**Comment by ltratt** [comment]
Hmm, I missed a warning from rustc: fixing.

**Comment by ltratt** [comment]
The third commit fixes the warning (TBH, it covers a case that I've never got close to seeing with real grammars, though one can trigger it with artificially tiny examples).

**Comment by ptersilie** [comment]
Looks good. You want to rebase the last commit or is it okay this way?

**Comment by ltratt** [comment]
I was just about to squash it before I realised that it actually makes more sense to be separate. So I'd suggest we merge as-is if you're OK with that.

**Comment by ptersilie** [comment]
I'm ok with that. Merged!

**Pull request merged**
