### PR TITLE
Tidyups

### PR DESCRIPTION
**Pull request by ltratt**
[This needs https://github.com/softdevteam/cfgrammar/pull/21 to be merged first. When that's merged, the Travis tests on this PR can be kicked and, hopefully, will then pass.]

These are a few mostly simple tidy-ups, each commit being fairly isolated, and hopefully adequately documented.

The only commit which requires much thought is 292a4bf14ef63ce681f8fbc8a0bbf270a196416f, which replaces the previous notions of separate insertion / deletion costs for a terminal with a single function (i.e. from now on a token has the same cost for being inserted as for being deleted).

### CODE REVIEW

**Comment by ptersilie** [comment]
Agreed on the term costs. Also see no reason why insertion would be cheaper or more costly than deletion. Waiting for merge of https://github.com/softdevteam/cfgrammar/pull/21 and tests.

**Comment by ltratt** [comment]
I think https://github.com/softdevteam/cfgrammar/pull/21 is probably ready for merging? Then I can kick the tests here off.

**Comment by ltratt** [comment]
I've kicked the builds.

**Comment by ptersilie** [comment]
Poor builds.

**Comment by ltratt** [comment]
OK, the tests are happy (even if the builds were unhappy about being kicked).

**Comment by ptersilie** [comment]
Merged!

**Pull request merged**
