### PR TITLE
Reflect changes in cfgrammar.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
[I've rekicked the build.]

**Comment by ltratt** [comment]
OK, there's something here I need to check, so please wait on this one for a while.

**Comment by snim2** [comment]
Time to kick this one again?

**Comment by ltratt** [comment]
Yep, I've been kicking things merrily.

**Comment by ltratt** [comment]
OK, fixed and ready for review.

**Comment by snim2** [comment]
Code looks OK to me.

**Pull request merged**
