### PR TITLE
Be more flexible about what nonterminal and terminal names can be.

### PR DESCRIPTION
**Pull request by ltratt**
It's not entirely clear to me if this is exactly what Yacc does, but the
previous rules were definitely too restrictive. This makes porting examples
from other sources quite a bit easier.

### CODE REVIEW

**Comment by ltratt** [comment]
I'm not sure this is quite right: the AST parser definitely expects that all token names are in `grammar.tokens`. So if we see a token we haven't seen before, I think we need to add it to that.

**Comment by ptersilie** [comment]
Hmm, unfortunately that is not how yacc grammars work though. :(

**Comment by ptersilie** [comment]
I think we need two lists then. One that has all regular tokens, and one that has the tokens defined by `%token`.

**Comment by ltratt** [comment]
I don't think we need two lists. If I understand correctly, when you see a token that you haven't seen before, add it to `grm.tokens` (or whatever it's called) and all should be good.

**Comment by ptersilie** [comment]
I don't think so. Let's say I have this grammar:

```
S : b 'b'
b: 'a'
```

Then 'b' will be added to %token. But then the nonterminal b won't be treated as a nonterminal anymore.

**Comment by ltratt** [comment]
I'm not 100% sure, but I'm not convinced this is will be an issue. Can you put in a test case and then we can check what the code actually does?

**Comment by ptersilie** [comment]
I don't know how the new `Grammar` uses the tokens defined in `%token`. But at least the changes I made to the verifier will now not complain about this grammar

```
S : b 'b'
```
while it should complain that the nonterminal 'b' is not defined.

I will add a test case.

**Pull request merged**
